### PR TITLE
feat: upload data endpoint

### LINKED ISSUE #3: WebAPI Endpoints: Data Upload
# Issue description
*Describe your issue in detail here*
Implement all endpoints required for effective data upload. This will initially exclude regex settings.

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

### PR DESCRIPTION
**Pull request by Claiyc**
# PR description
*Describe your changes in detail here*
This adds a simple endpoint for uploading data. Partly refactores get data aswell.

# Definition Of Done (DoD)
*This PR can be squashed / merged if*
- [x] a developer is assigned
- [x] the PR is NOT estimated
- [x] the PR is labeled
- [x] the PR is NOT assigned to the current sprint
- [x] a meaningful title has been set according to https://www.conventionalcommits.org/
- [x] the PR is described in detail
- [x] the PR links to an issue
- [x] the PR has been reviewed

*Add additional conditions here if necessary for this PR*
fixes #3

### CODE REVIEW

**Comment by Claiyc** [comment]
This definitely needs to be refactored at some point. First we need to figure out what the redis internal data structure looks like (and for that I need to better understand how redis works). For now this at least should work.

**Comment by Claiyc** [comment]
finally fixed it... did I say that I hate promises before?

**Comment by Claiyc** [comment]
after doing some additional research, I think this actually isn't the worst solution... The current issue is that our current data structure does not support something like "get all values from a set of keys". Instead we currently save each match as a single key-value pair and match them together using regular sets. The concept of redis hashes sounds much more promising here, however I don't quite understand yet how that can work using redisJSON.

Works for now, however for production use we'll have to implement some sort of limit. Since we do store the timestamp of a match already, it might be a solution to implement an endpoint that takes a timestamp range as parameter

**Comment by Claiyc** [comment]
regarding testing this... It is actually required to put in the Content: application/json header!

**Comment by roman533** [comment]
Bildschirmfoto 2023-05-25 um 08 39 53
lgtm

**Review by roman533 — APPROVED** [review]
Works fine

**Pull request merged**
